#!/bin/bash

source functions.sh
BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "WORKER0_HOST_PUBLIC ------- $WORKER0_HOST_PUBLIC "
echo "WORKER0_IP_PUBLIC --------- $WORKER0_IP_PUBLIC "
echo "WORKER1_HOST_PUBLIC ------- $WORKER1_HOST_PUBLIC "
echo "WORKER1_IP_PUBLIC --------- $WORKER1_IP_PUBLIC "
echo "CTRL0_HOST_PRIVATE -------- $CTRL0_HOST_PRIVATE "
echo "CTRL0_HOST_PUBLIC --------- $CTRL0_HOST_PUBLIC "
echo "CTRL0_IP_PUBLIC ----------- $CTRL0_IP_PUBLIC "
echo "CTRL0_IP_PRIVATE ---------- $CTRL0_IP_PRIVATE "
echo "CTRL1_HOST_PRIVATE -------- $CTRL1_HOST_PRIVATE "
echo "CTRL1_HOST_PUBLIC --------- $CTRL1_HOST_PUBLIC "
echo "CTRL1_IP_PUBLIC ----------- $CTRL1_IP_PUBLIC "
echo "CTRL1_IP_PRIVATE ---------- $CTRL1_IP_PRIVATE "
echo "API_LB_HOST_PUBLIC -------- $API_LB_HOST_PUBLIC "
echo "API_LB_IP_PUBLIC ---------- $API_LB_IP_PUBLIC "
echo "API_LB_HOST_PRIVATE ------- $API_LB_HOST_PRIVATE "
echo "API_LB_IP_PRIVATE --------- $API_LB_IP_PRIVATE "


